### ISSUE TITLE
HTML block not responding

### ISSUE THREAD

**Issue by atorrance** [ajfick/Pebbles#1]
Hey AJ thank you for sharing! I followed your instructions completely, however the HTML block's buttons (date pickers and 'Go') do not seem to work. When the buttons are clicked nothing happens, no date picker shows up on the calendar and no data shows up in the Dynamic Data block. The page doesn't even try to load anything The block has the correct lava permissions as well as globally. Any idea why this would be happening?

![giving report](https://user-images.githubusercontent.com/34725020/44235543-e336ce00-a177-11e8-8b57-a5ef4ce79954.gif)

**Comment by ajfick** [comment]
The Date Pickers use query to open the actual picker modal and the Go button basically just calls a `window.location()` and appends the query string. So I would say make sure that you are capable of running jaunty scripts on that page. Maybe just a simple `console.log` to see that it executed as expected.

**Comment by ajfick** [comment]
And actually, because that block is JS the page will require a reload before it will work (I think) so if you haven’t reloaded the page try that as well!

**Comment by atorrance** [comment]
Everything seems to be fine on my page. I re-created it on the demo site for you to see: [http://rock.rocksolidchurchdemo.com/page/6460](url)

**Comment by ajfick** [comment]
@atorrance I just updated the ReportParametersBlock.lava file and it seems to work as expected on the Rock Demo site. Give that a shot and let me know if it’s all good!

**Comment by atorrance** [comment]
It works great now, thanks!
